# Generated by Django 4.0.5 on 2022-10-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_categories_post_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
